/// Train travel package model for featured train journeys
class TrainPackage {
  final String id;
  final String name;
  final String trainNumber;
  final String fromStation;
  final String toStation;
  final String departureTime;
  final String duration;
  final String trainClass;
  final double price;
  final String imageUrl;
  final List<String> amenities;
  final bool isFeatured;
  final String packageType; // 'express', 'sleeper', 'business'
  final bool roundTrip;

  TrainPackage({
    required this.id,
    required this.name,
    required this.trainNumber,
    required this.fromStation,
    required this.toStation,
    required this.departureTime,
    required this.duration,
    required this.trainClass,
    required this.price,
    required this.imageUrl,
    required this.amenities,
    this.isFeatured = false,
    this.roundTrip = true,
    required this.packageType,
  });
}

/// Featured train packages for unified home screen
final List<TrainPackage> featuredTrainPackages = [
  TrainPackage(
    id: 'tp1',
    name: 'Green Line Express',
    trainNumber: '5UP',
    fromStation: 'Karachi Cantt',
    toStation: 'Lahore Junction',
    departureTime: '11:00 PM',
    duration: '13h 30m',
    trainClass: 'AC Sleeper',
    price: 9800,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    packageType: 'sleeper',
  ),
  TrainPackage(
    id: 'tp2',
    name: 'Tezgam Express',
    trainNumber: '1UP',
    fromStation: 'Karachi Cantt',
    toStation: 'Rawalpindi',
    departureTime: '06:00 AM',
    duration: '15h',
    trainClass: 'AC Business',
    price: 10800,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Business', 'Meals'],
    isFeatured: true,
    packageType: 'business',
  ),
  TrainPackage(
    id: 'tp3',
    name: 'Pakistan Business Express',
    trainNumber: '9UP',
    fromStation: 'Karachi Cantt',
    toStation: 'Lahore Junction',
    departureTime: '03:00 PM',
    duration: '13h',
    trainClass: 'AC Business',
    price: 9800,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Business', 'Premium Meals'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'business',
  ),
  TrainPackage(
    id: 'tp4',
    name: 'Allama Iqbal Express',
    trainNumber: '17UP',
    fromStation: 'Karachi Cantt',
    toStation: 'Lahore Junction',
    departureTime: '07:30 PM',
    duration: '13h 45m',
    trainClass: 'AC Sleeper',
    price: 9700,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    packageType: 'sleeper',
  ),
  TrainPackage(
    id: 'tp5',
    name: 'Khyber Mail',
    trainNumber: '7UP',
    fromStation: 'Karachi Cantt',
    toStation: 'Peshawar Cantt',
    departureTime: '02:00 PM',
    duration: '18h 30m',
    trainClass: 'AC Lower',
    price: 9800,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Lower', 'Meals'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'express',
  ),
  TrainPackage(
    id: 'tp6',
    name: 'Karachi Express',
    trainNumber: '14DN',
    fromStation: 'Lahore Junction',
    toStation: 'Karachi Cantt',
    departureTime: '10:30 PM',
    duration: '13h 30m',
    trainClass: 'AC Sleeper',
    price: 9900,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    packageType: 'sleeper',
  ),

  // ── KARACHI (KHI) — 3 more (tp1–tp5 already exist → 8 total) ─────────────
  TrainPackage(
    id: 'tp_khi_06',
    name: 'Mehran Express',
    trainNumber: '86UP',
    fromStation: 'Karachi Cantt',
    toStation: 'Multan Cantt',
    departureTime: '08:00 AM',
    duration: '8h 30m',
    trainClass: 'AC Sleeper',
    price: 5900,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    packageType: 'sleeper',
  ),
  TrainPackage(
    id: 'tp_khi_07',
    name: 'Hyderabad Express',
    trainNumber: '61UP',
    fromStation: 'Karachi Cantt',
    toStation: 'Hyderabad Jn',
    departureTime: '08:30 AM',
    duration: '2h 15m',
    trainClass: 'AC Seater',
    price: 1200,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Seater', 'Snacks'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'express',
  ),
  TrainPackage(
    id: 'tp_khi_08',
    name: 'Sukkur Express',
    trainNumber: '73UP',
    fromStation: 'Karachi Cantt',
    toStation: 'Sukkur',
    departureTime: '06:30 PM',
    duration: '5h 45m',
    trainClass: 'AC Lower',
    price: 2800,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Lower', 'Meals'],
    isFeatured: true,
    packageType: 'express',
  ),

  // ── LAHORE (LHE) — 7 more (tp6 already exists → 8 total) ─────────────────
  TrainPackage(
    id: 'tp_lhe_02',
    name: 'Islamabad Express',
    trainNumber: '11UP',
    fromStation: 'Lahore Junction',
    toStation: 'Rawalpindi',
    departureTime: '07:00 AM',
    duration: '4h 30m',
    trainClass: 'AC Seater',
    price: 2600,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Seater', 'Snacks'],
    isFeatured: true,
    packageType: 'express',
  ),
  TrainPackage(
    id: 'tp_lhe_03',
    name: 'Peshawar Express',
    trainNumber: '3UP',
    fromStation: 'Lahore Junction',
    toStation: 'Peshawar Cantt',
    departureTime: '09:00 AM',
    duration: '5h 45m',
    trainClass: 'AC Sleeper',
    price: 4200,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'sleeper',
  ),
  TrainPackage(
    id: 'tp_lhe_04',
    name: 'Shah Hussain Express',
    trainNumber: '23UP',
    fromStation: 'Lahore Junction',
    toStation: 'Multan Cantt',
    departureTime: '06:00 PM',
    duration: '3h 30m',
    trainClass: 'AC Business',
    price: 3300,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Business', 'Premium Meals'],
    isFeatured: true,
    packageType: 'business',
  ),
  TrainPackage(
    id: 'tp_lhe_05',
    name: 'Chenab Express',
    trainNumber: '45UP',
    fromStation: 'Lahore Junction',
    toStation: 'Faisalabad Jn',
    departureTime: '08:00 AM',
    duration: '2h 15m',
    trainClass: 'AC Seater',
    price: 830,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Seater', 'Snacks'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'express',
  ),
  TrainPackage(
    id: 'tp_lhe_06',
    name: 'Rehman Baba Express',
    trainNumber: '31UP',
    fromStation: 'Lahore Junction',
    toStation: 'Peshawar Cantt',
    departureTime: '11:30 PM',
    duration: '6h 15m',
    trainClass: 'AC Sleeper',
    price: 4400,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    packageType: 'sleeper',
  ),
  TrainPackage(
    id: 'tp_lhe_07',
    name: 'Karakoram Express',
    trainNumber: '25UP',
    fromStation: 'Lahore Junction',
    toStation: 'Peshawar Cantt',
    departureTime: '11:00 AM',
    duration: '5h 30m',
    trainClass: 'AC Business',
    price: 4200,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Business', 'Premium Meals'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'business',
  ),
  TrainPackage(
    id: 'tp_lhe_08',
    name: 'Quetta Express',
    trainNumber: '17UP',
    fromStation: 'Lahore Junction',
    toStation: 'Quetta',
    departureTime: '08:30 PM',
    duration: '18h 30m',
    trainClass: 'AC Sleeper',
    price: 7500,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    packageType: 'sleeper',
  ),

  // ── RAWALPINDI/ISB (RWP) — 5 packages (Rawalpindi station serves ISB) ────
  TrainPackage(
    id: 'tp_rwp_01',
    name: 'Tezgam Express',
    trainNumber: '2DN',
    fromStation: 'Rawalpindi',
    toStation: 'Karachi Cantt',
    departureTime: '03:00 PM',
    duration: '15h',
    trainClass: 'AC Business',
    price: 10900,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Business', 'Meals'],
    isFeatured: true,
    packageType: 'business',
  ),
  TrainPackage(
    id: 'tp_rwp_02',
    name: 'Islamabad Express',
    trainNumber: '12DN',
    fromStation: 'Rawalpindi',
    toStation: 'Lahore Junction',
    departureTime: '06:30 AM',
    duration: '4h 30m',
    trainClass: 'AC Seater',
    price: 2800,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Seater', 'Snacks'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'express',
  ),
  TrainPackage(
    id: 'tp_rwp_03',
    name: 'Peshawar Express',
    trainNumber: '4DN',
    fromStation: 'Rawalpindi',
    toStation: 'Peshawar Cantt',
    departureTime: '09:00 AM',
    duration: '2h 30m',
    trainClass: 'AC Seater',
    price: 1400,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Seater', 'Snacks'],
    isFeatured: true,
    packageType: 'express',
  ),
  TrainPackage(
    id: 'tp_rwp_04',
    name: 'Punjab Express',
    trainNumber: '36DN',
    fromStation: 'Rawalpindi',
    toStation: 'Multan Cantt',
    departureTime: '07:00 PM',
    duration: '5h 30m',
    trainClass: 'AC Sleeper',
    price: 4300,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'sleeper',
  ),
  TrainPackage(
    id: 'tp_rwp_05',
    name: 'Margalla Express',
    trainNumber: '57DN',
    fromStation: 'Rawalpindi',
    toStation: 'Faisalabad Jn',
    departureTime: '10:00 AM',
    duration: '4h',
    trainClass: 'AC Seater',
    price: 2200,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Seater', 'Snacks'],
    isFeatured: true,
    packageType: 'express',
  ),

  // ── PESHAWAR (PEW) — 5 packages ──────────────────────────────────────────
  TrainPackage(
    id: 'tp_pew_01',
    name: 'Khyber Mail',
    trainNumber: '8DN',
    fromStation: 'Peshawar Cantt',
    toStation: 'Karachi Cantt',
    departureTime: '07:30 AM',
    duration: '18h 30m',
    trainClass: 'AC Lower',
    price: 9900,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Lower', 'Meals'],
    isFeatured: true,
    packageType: 'express',
  ),
  TrainPackage(
    id: 'tp_pew_02',
    name: 'Awami Express',
    trainNumber: '64DN',
    fromStation: 'Peshawar Cantt',
    toStation: 'Lahore Junction',
    departureTime: '06:00 AM',
    duration: '5h 45m',
    trainClass: 'AC Sleeper',
    price: 4300,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'sleeper',
  ),
  TrainPackage(
    id: 'tp_pew_03',
    name: 'Peshawar Express',
    trainNumber: '5DN',
    fromStation: 'Peshawar Cantt',
    toStation: 'Rawalpindi',
    departureTime: '09:30 AM',
    duration: '2h 30m',
    trainClass: 'AC Seater',
    price: 1400,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Seater', 'Snacks'],
    isFeatured: true,
    packageType: 'express',
  ),
  TrainPackage(
    id: 'tp_pew_04',
    name: 'Frontier Mail',
    trainNumber: '22DN',
    fromStation: 'Peshawar Cantt',
    toStation: 'Multan Cantt',
    departureTime: '11:00 AM',
    duration: '7h 30m',
    trainClass: 'AC Sleeper',
    price: 4600,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'sleeper',
  ),
  TrainPackage(
    id: 'tp_pew_05',
    name: 'Faisalabad Express',
    trainNumber: '44DN',
    fromStation: 'Peshawar Cantt',
    toStation: 'Faisalabad Jn',
    departureTime: '02:00 PM',
    duration: '5h',
    trainClass: 'AC Seater',
    price: 3100,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Seater', 'Snacks'],
    isFeatured: true,
    packageType: 'express',
  ),

  // ── MULTAN (MUX) — 3 packages ─────────────────────────────────────────────
  TrainPackage(
    id: 'tp_mux_01',
    name: 'Multan Express',
    trainNumber: '82DN',
    fromStation: 'Multan Cantt',
    toStation: 'Karachi Cantt',
    departureTime: '10:00 PM',
    duration: '9h',
    trainClass: 'AC Sleeper',
    price: 6000,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    packageType: 'sleeper',
  ),
  TrainPackage(
    id: 'tp_mux_02',
    name: 'Shah Hussain Express',
    trainNumber: '24DN',
    fromStation: 'Multan Cantt',
    toStation: 'Lahore Junction',
    departureTime: '08:00 AM',
    duration: '3h 30m',
    trainClass: 'AC Business',
    price: 2800,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Business', 'Premium Meals'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'business',
  ),
  TrainPackage(
    id: 'tp_mux_03',
    name: 'Shalimar Express',
    trainNumber: '6DN',
    fromStation: 'Multan Cantt',
    toStation: 'Rawalpindi',
    departureTime: '03:00 PM',
    duration: '5h 15m',
    trainClass: 'AC Sleeper',
    price: 4000,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    packageType: 'sleeper',
  ),

  // ── FAISALABAD (LYP) — 3 packages ────────────────────────────────────────
  TrainPackage(
    id: 'tp_lyp_01',
    name: 'Chenab Express',
    trainNumber: '46DN',
    fromStation: 'Faisalabad Jn',
    toStation: 'Lahore Junction',
    departureTime: '07:00 AM',
    duration: '2h 15m',
    trainClass: 'AC Seater',
    price: 820,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Seater', 'Snacks'],
    isFeatured: true,
    packageType: 'express',
  ),
  TrainPackage(
    id: 'tp_lyp_02',
    name: 'Lyallpur Express',
    trainNumber: '78DN',
    fromStation: 'Faisalabad Jn',
    toStation: 'Karachi Cantt',
    departureTime: '09:00 PM',
    duration: '11h',
    trainClass: 'AC Sleeper',
    price: 4400,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'sleeper',
  ),
  TrainPackage(
    id: 'tp_lyp_03',
    name: 'Margalla Express',
    trainNumber: '60DN',
    fromStation: 'Faisalabad Jn',
    toStation: 'Rawalpindi',
    departureTime: '05:30 PM',
    duration: '3h 30m',
    trainClass: 'AC Seater',
    price: 2270,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Seater', 'Snacks'],
    isFeatured: true,
    packageType: 'express',
  ),

  // ── HYDERABAD (HYD) — 3 packages (on KHI-LHE main PR line) ──────────────
  TrainPackage(
    id: 'tp_hyd_01',
    name: 'Indus Express',
    trainNumber: '22UP',
    fromStation: 'Hyderabad Jn',
    toStation: 'Lahore Junction',
    departureTime: '06:00 PM',
    duration: '11h',
    trainClass: 'AC Sleeper',
    price: 8200,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    packageType: 'sleeper',
  ),
  TrainPackage(
    id: 'tp_hyd_02',
    name: 'Hyderabad Express',
    trainNumber: '62DN',
    fromStation: 'Hyderabad Jn',
    toStation: 'Karachi Cantt',
    departureTime: '08:30 AM',
    duration: '2h 15m',
    trainClass: 'AC Seater',
    price: 1200,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Seater', 'Snacks'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'express',
  ),
  TrainPackage(
    id: 'tp_hyd_03',
    name: 'Sindh Express',
    trainNumber: '36UP',
    fromStation: 'Hyderabad Junction',
    toStation: 'Rawalpindi',
    departureTime: '10:00 PM',
    duration: '13h 30m',
    trainClass: 'AC Sleeper',
    price: 10300,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    packageType: 'sleeper',
  ),

  // ── SUKKUR (SKR) — 3 packages (on KHI-LHE main PR line) ─────────────────
  TrainPackage(
    id: 'tp_skr_01',
    name: 'Bhittai Express',
    trainNumber: '48UP',
    fromStation: 'Sukkur Station',
    toStation: 'Karachi Cantt',
    departureTime: '08:00 PM',
    duration: '5h 30m',
    trainClass: 'AC Lower',
    price: 2700,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Lower', 'Meals'],
    isFeatured: true,
    packageType: 'express',
  ),
  TrainPackage(
    id: 'tp_skr_02',
    name: 'Sukkur Express',
    trainNumber: '74UP',
    fromStation: 'Sukkur Station',
    toStation: 'Lahore Junction',
    departureTime: '10:00 AM',
    duration: '7h 30m',
    trainClass: 'AC Sleeper',
    price: 4700,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    roundTrip: false,
    packageType: 'sleeper',
  ),
  TrainPackage(
    id: 'tp_skr_03',
    name: 'Indus Valley Express',
    trainNumber: '92UP',
    fromStation: 'Sukkur Station',
    toStation: 'Rawalpindi',
    departureTime: '07:00 PM',
    duration: '9h',
    trainClass: 'AC Sleeper',
    price: 5300,
    imageUrl:
        'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    amenities: ['AC Sleeper', 'Meals'],
    isFeatured: true,
    packageType: 'sleeper',
  ),
];
