from prompts.master_agent import MASTER_SYSTEM, MASTER_ROUTING_PROMPT
from prompts.clarification import (
    CLARIFICATION_SYSTEM,
    ENTITY_EXTRACTION_PROMPT,
    CLARIFICATION_QUESTION_PROMPT,
    QUERY_CLASSIFICATION_PROMPT,
)
from prompts.memory import (
    MEMORY_SYSTEM,
    PREFERENCE_EXTRACTION_PROMPT,
    CONVERSATION_SUMMARY_PROMPT,
    CONTEXT_INJECTION_PROMPT,
)
from prompts.weather import WEATHER_SYSTEM, WEATHER_SUMMARY_PROMPT, WEATHER_TRIP_ADVICE_PROMPT
from prompts.transport import TRANSPORT_SYSTEM, FLIGHT_RESULTS_PROMPT, TRAIN_RESULTS_PROMPT, TRANSPORT_COMPARISON_PROMPT
from prompts.hotel import HOTEL_SYSTEM, HOTEL_RESULTS_PROMPT, HOTEL_RECOMMENDATION_PROMPT
from prompts.healthcare import HEALTHCARE_SYSTEM, HEALTHCARE_RESULTS_PROMPT, HEALTHCARE_ADVICE_PROMPT
from prompts.itinerary import ITINERARY_SYSTEM, ITINERARY_BUILD_PROMPT, ITINERARY_SUMMARY_PROMPT
from prompts.budget import BUDGET_SYSTEM, BUDGET_ESTIMATE_PROMPT, BUDGET_COMPARISON_PROMPT
from prompts.recommendation import (
    RECOMMENDATION_SYSTEM,
    DESTINATION_RECOMMENDATION_PROMPT,
    ACTIVITY_RECOMMENDATION_PROMPT,
    SIMILAR_DESTINATIONS_PROMPT,
)
from prompts.booking import BOOKING_SYSTEM, BOOKING_CONFIRMATION_PROMPT, BOOKING_ERROR_PROMPT, POST_BOOKING_PROMPT

__all__ = [
    "MASTER_SYSTEM", "MASTER_ROUTING_PROMPT",
    "CLARIFICATION_SYSTEM", "ENTITY_EXTRACTION_PROMPT", "CLARIFICATION_QUESTION_PROMPT", "QUERY_CLASSIFICATION_PROMPT",
    "MEMORY_SYSTEM", "PREFERENCE_EXTRACTION_PROMPT", "CONVERSATION_SUMMARY_PROMPT", "CONTEXT_INJECTION_PROMPT",
    "WEATHER_SYSTEM", "WEATHER_SUMMARY_PROMPT", "WEATHER_TRIP_ADVICE_PROMPT",
    "TRANSPORT_SYSTEM", "FLIGHT_RESULTS_PROMPT", "TRAIN_RESULTS_PROMPT", "TRANSPORT_COMPARISON_PROMPT",
    "HOTEL_SYSTEM", "HOTEL_RESULTS_PROMPT", "HOTEL_RECOMMENDATION_PROMPT",
    "HEALTHCARE_SYSTEM", "HEALTHCARE_RESULTS_PROMPT", "HEALTHCARE_ADVICE_PROMPT",
    "ITINERARY_SYSTEM", "ITINERARY_BUILD_PROMPT", "ITINERARY_SUMMARY_PROMPT",
    "BUDGET_SYSTEM", "BUDGET_ESTIMATE_PROMPT", "BUDGET_COMPARISON_PROMPT",
    "RECOMMENDATION_SYSTEM", "DESTINATION_RECOMMENDATION_PROMPT", "ACTIVITY_RECOMMENDATION_PROMPT", "SIMILAR_DESTINATIONS_PROMPT",
    "BOOKING_SYSTEM", "BOOKING_CONFIRMATION_PROMPT", "BOOKING_ERROR_PROMPT", "POST_BOOKING_PROMPT",
]
